#!/bin/bash

CmdName=$(basename "$0")

echo "$0" 1>&2

Syntax="${CmdName} [-a Atlas][-A AtlasDirectory][-c ConfigJsonFile][-i IdString][-o OutputDir][-l ShiftLeft][-r ShiftRight][-I ShiftIcv][-1 T1NiftiFile][-2 T2NiftiFile][-t T1NiftiFileTrimmed][-v][-w WorkDir][-q QaLocation]"

while getopts a:A:c:i:o:l:r:I:1:2:t:w:vq: arg 
do
	case "$arg" in
	       	a|A|c|i|o|l|r|I|1|2|t|w|v|q)
			eval "opt_${arg}='${OPTARG:=1}'"
			;;

	esac
done

shift $(("$OPTIND" - 1))

Atlas="$opt_a"
AtlasDirectory="$opt_A"
ConfigJsonFile="$opt_c"
IdString="$opt_i"
OutputDir="$opt_o"
SHIFT_LEFT="$opt_l"
SHIFT_RIGHT="$opt_r"
SHIFT_ICV="$opt_I"
T1NiftiFile="$opt_1"
T1NiftiFileTrimmed="$opt_t"
T2NiftiFile="$opt_2"
WorkDir="$opt_w"


if [ "$T1NiftiFile" == "$T2NiftiFile" ]
then
	T2InputNeeded=
else
	T2InputNeeded=1
fi

AshsPrefix=$(basename "$WorkDir")

AshsAtlasConfigFile="/app/AshsAtlasesConfig.json"
AtlasJson=$(jq -r 'select(.Atlas == "'"${Atlas}"'")' "$AshsAtlasConfigFile")

function sys {
    [ -n "${opt_n}${opt_v}" ] && echo "$(date): $@" 1>&2
    [ -n "$opt_n" ] || "$@"
}

function uploadQaFile {
        local ProjectPath="$1"
        local File="$2"
	local Tags=( $(echo "$3" | sed 's/,/ /g') )


        case "$File" in
                *left*.png)
			Tags+=(ReadyforASHSQC-left)
                        ;;

                *right*.png)
			Tags+=(ReadyforASHSQC-right)
                        ;;

        esac

	sys fwuploadfile -p "$ProjectPath" -t "$(echo ${Tags[@]} | sed 's/  */,/g')" "$File"
}

	ItkSnapFile=${OutputDir}/${IdString}_${Atlas}_results.itksnap

	SnaplabelsInputTxtFile="${AtlasDirectory}/snap/snaplabels.txt"

	sys ls "$WorkDir"

	#
	# Older versions had different tags for T1 under ASHS-HarP than the other atlases
	#
	#if [ "$Service" == "ASHS-HarP" ]
	#then
	#    	T1Tag=T1
	#else

	T1Tag=T1-MRI
	T2Tag=T2-MRI
	T1OutputNiftiFile="${OutputDir}/"$(basename "$T1NiftiFileTrimmed")
	sys cp "$T1NiftiFileTrimmed" "$T1OutputNiftiFile"

	sys c3d "$T1OutputNiftiFile" -info

	ITKSnapCmd=( itksnap-wt -layers-add-anat "$T1OutputNiftiFile" -tags-add "$T1Tag" -layers-list -o "$ItkSnapFile" )

	if [ -n "$T2InputNeeded" ]
	then
		T2OutputNiftiFile="${OutputDir}/"$(basename "$T2NiftiFile")
		sys cp "$T2NiftiFile" "$T2OutputNiftiFile"

		ITKSnapCmd=( itksnap-wt -layers-add-anat "$T1OutputNiftiFile" -tags-add "$T1Tag" -layers-add-anat "$T2OutputNiftiFile" -tags-add "$T2Tag" -layers-list -o "$ItkSnapFile" )
	fi

	# Create T1 or T1+T2 MRI result file
	sys "${ITKSnapCmd[@]}"

	AcquisitionId=$(jq -r '.inputs.T1w.hierarchy.id' "$ConfigJsonFile")
	JobId=$(jq -r '.job.id' "$ConfigJsonFile")
	JobUrl="https://upenn.flywheel.io/#/jobs/${JobId}"
	DateTime=$(date)
	
	if [ "$Atlas" == "ASHS-HarP" ]
	then

		LeftHippocampusVolume=$(sys awk '{print $5}' ${WorkDir}/final/${AshsPrefix}_left_bootstrap_corr_nogray_volumes.txt)
		RightHippocampusVolume=$(sys awk '{print $5}' ${WorkDir}/final/${AshsPrefix}_right_bootstrap_corr_nogray_volumes.txt)
		sys fwUpdateInfo -f -p .PICSL_sMRI_biomarkers -j "+={\"LeftHippocampusVolume\": ${LeftHippocampusVolume}, \"RightHippocampusVolume\": ${RightHippocampusVolume} }" "$AcquisitionId"
	fi

	if [ "$Atlas" != "ASHS-ICV" ]
	then
		for what in heur corr_usegray corr_nogray
		do
		    sys c3d														\
		    		"$WorkDir/final/${AshsPrefix}_left_lfseg_${what}.nii.gz" -shift $SHIFT_LEFT -replace $SHIFT_LEFT 0	\
				"$WorkDir/final/${AshsPrefix}_right_lfseg_${what}.nii.gz" -shift $SHIFT_RIGHT -replace $SHIFT_RIGHT 0	\
				-add -type uchar 											\
				-o "${OutputDir}/${IdString}_${Atlas}_lfseg_${what}.nii.gz"

		    sys c3d "${OutputDir}/${IdString}_${Atlas}_lfseg_${what}.nii.gz" -info
		done

		sys cp "${WorkDir}/tse.nii.gz" "${OutputDir}/${IdString}_${Atlas}_tse.nii.gz"

	# Add in the next 3 layers
		sys itksnap-wt -i "$ItkSnapFile" \
		   -layers-set-main "${OutputDir}/${IdString}_${Atlas}_tse.nii.gz" \
		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_usegray.nii.gz" -psn "JLF/CL result" \
		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_nogray.nii.gz" -psn "JLF/CL-lite result" \
		   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_heur.nii.gz" -psn "JLF result" \
		   -labels-clear \
		   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_LEFT "Left %s" \
		   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_RIGHT "Right %s" \
		   -o "$ItkSnapFile"

		ItkSnapIcvFile="${OutputDir}/${IdString}_ASHS-ICV_results.itksnap"
		ItkSnapHarPIcvFile="${OutputDir}/${IdString}_ASHS-HarP-ICV_results.itksnap"
		if [ -e "$ItkSnapIcvFile" ]
		then
			sys itksnap-wt -i "$ItkSnapIcvFile" \
		           -layers-set-main "${OutputDir}/${IdString}_${Atlas}_tse.nii.gz" \
			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_usegray.nii.gz" -psn "JLF/CL result" \
			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_corr_nogray.nii.gz" -psn "JLF/CL-lite result" \
			   -las "${OutputDir}/${IdString}_${Atlas}_lfseg_heur.nii.gz" -psn "JLF result" \
			   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_LEFT "Left %s" \
			   -labels-add "$SnaplabelsInputTxtFile" $SHIFT_RIGHT "Right %s" \
			   -o "$ItkSnapHarPIcvFile"
		fi

        fi

	if [ "$Atlas" == "ASHS-ICV" ]
	then
		# Add the ICV image to the project
		sys c3d														\
			"$WorkDir/final/${AshsPrefix}_left_lfseg_corr_nogray.nii.gz" -shift $SHIFT_ICV -replace $SHIFT_ICV 0     \
    			-type uchar -o "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz"


		sys cp "${WorkDir}/tse.nii.gz" "${OutputDir}/${IdString}_${Atlas}_tse.nii.gz"

		sys c3d "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz" -info

		ICV=$(c3d "${WorkDir}/final/${AshsPrefix}_left_lfseg_corr_nogray.nii.gz" -dup -lstat | awk '$1 == 1 {print $7}')

		sys fwUpdateInfo -f -p .PICSL_sMRI_biomarkers -j "+={\"ICV\": ${ICV} }" "$AcquisitionId"

  		sys itksnap-wt -i "$ItkSnapFile" \
    		   -las "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz" -psn "ICV" \
		   -labels-clear \
    		   -labels-add "$SnaplabelsInputTxtFile" "$SHIFT_ICV" "%s" \
    		   -o "$ItkSnapFile"

		ItkSnapHarPFile="${OutputDir}/${IdString}_ASHS-HarP_results.itksnap"
	 	ItkSnapHarPIcvFile="${OutputDir}/${IdString}_ASHS-HarP-ICV_results.itksnap"
		if [ -e "$ItkSnapHarPFile" ]
		then
  			sys itksnap-wt -i "$ItkSnapHarPFile" \
    			   -las "${OutputDir}/${IdString}_${Atlas}_icv.nii.gz" -psn "ICV" \
    			   -labels-add "$SnaplabelsInputTxtFile" "$SHIFT_ICV" "%s" \
    			   -o "$ItkSnapHarPIcvFile"
		fi
	fi

	regex=$(echo "$AtlasJson" | jq -r 'if .QaFileRegEx then .QaFileRegEx | @csv else empty end' | sed -r 's/"(.*)"$/(\1)/; s/","/)|(/g' )
	if [ -z "$regex" ]
	then
		regex="^$"
	fi

	[ -n "$opt_v" ] && find "${WorkDir}" -type f | grep -E "$regex"

    	for i in $(find "${WorkDir}" -type f | grep -E "$regex")
    	do
    	    BaseName=$(basename "$i" )

	    echo "opt_q = '$opt_q'" 1>&2
	    echo "BaseName = '$BaseName'" 1>&2
	    echo "WorkDir = '$WorkDir'" 1>&2
	    echo "OutputDir = '$OutputDir'" 1>&2
	    echo "IdString = '$IdString'" 1>&2

	    NewBaseName=$(echo "$BaseName" | sed "s/${AshsPrefix}_//")
	    OutputFile=$(echo "${OutputDir}/${IdString}_${Atlas}_${NewBaseName}" | sed 's/ICV_qa_seg_multiatlas_corr_nogray_left_qa/ICV_icv_qc/')

	    case "$opt_q" in
	        Analysis|analysis)
    		    sys cp "$i" "${OutputFile}"
		    ;;

	        "None"|"null")
		    true
		    ;;

		Acquisition|acquisition)
		    sys cp "$i" "$OutputFile"

		    sys uploadQaFile "$AcquisitionId"  "$OutputFile" "$Atlas"
		    ;;

		*)
		    sys cp "$i" "$OutputFile"

		    sys uploadQaFile "$opt_q"  "$OutputFile" "$Atlas"
		    ;;

            esac
	done

	sys txt2json -v -w "$WorkDir" -a "$Atlas" -j "$JobId" -d "$DateTime"  > "${OutputDir}/${Atlas}.json"
	sys fwUpdateInfo -f -p .PICSL_sMRI_biomarkers -j "{ \"$Atlas\": $(< ${OutputDir}/${Atlas}.json) }" "$AcquisitionId"

	fwget -1 "$AcquisitionId" | jq -r '.info.PICSL_sMRI_biomarkers' > "${OutputDir}/PICSL_sMRI_biomarkers.json"
	
	sys ls -l "$OutputDir"

	for i in output/*"${Atlas}"*.nii.gz
	do
		c3d "$i" -info
	done
